// Copyright (c) Bili Copilot. All rights reserved.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Xml;

namespace BiliCopilot.UI.ResourceGenerator;

/// <summary>
/// 编译期间获取资源文件并生成对应的枚举类型.
/// </summary>
[Generator]
public class ResourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 如果需要调试，取消下面的注释
        // if (!Debugger.IsAttached) Debugger.Launch();
        var additionalFiles = context.AdditionalTextsProvider.Where(f => f.Path.EndsWith(".resw", StringComparison.OrdinalIgnoreCase));
        var contents = additionalFiles.Select((file, cancellationToken) => file.GetText(cancellationToken).ToString());
        context.RegisterSourceOutput(contents, (spc, content) =>
        {
            ProcessResourceFile(content, spc);
        });
    }

    /// <summary>
    /// Escapes text to be safe inside an XML doc comment (/// &lt;summary&gt;).
    /// Handles: &amp;, &lt;, &gt;, double hyphen sequences, and leading/trailing hyphens.
    /// </summary>
    private static string EscapeForXmlComment(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        var sb = new StringBuilder(value.Length);
        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            switch (c)
            {
                case '&':
                    sb.Append("&amp;");
                    break;
                case '<':
                    sb.Append("&lt;");
                    break;
                case '>':
                    sb.Append("&gt;");
                    break;
                case '-':
                    // Prevent '--' which is illegal in XML comments
                    // Also prevent starting or ending with '-' which can be problematic
                    if (i + 1 < value.Length && value[i + 1] == '-')
                    {
                        // Replace the first hyphen with its Unicode lookalike (hyphen U+2010)
                        sb.Append('\u2010');
                        // Skip the next hyphen — it's safe as a single one
                        // but we still need to check it in the next iteration won't happen
                        // since we consume it here. However we should also check if there's a third.
                        i++; // skip second hyphen
                        // Check for third consecutive hyphen
                        if (i + 1 < value.Length && value[i + 1] == '-')
                        {
                            sb.Append('\u2010');
                            i++;
                        }
                    }
                    else if (sb.Length == 0 || EndsWithHyphenLikeChar(sb))
                    {
                        // Don't start a "word" segment that could form -- with previous content
                        // But single leading hyphens in things like "- 下载" are OK in practice,
                        // they don't form -- unless preceded by another hyphen
                        sb.Append('-');
                    }
                    else
                    {
                        sb.Append('-');
                    }
                    break;
                default:
                    sb.Append(c);
                    break;
            }
        }

        // Final safety pass: ensure result doesn't start or end with --
        var result = sb.ToString();
        while (result.StartsWith("--"))
            result = "\u2010" + result.Substring(2);
        while (result.EndsWith("--"))
            result = result.Substring(0, result.Length - 2) + "\u2010";

        return result;
    }

    private static bool EndsWithHyphenLikeChar(StringBuilder sb)
    {
        if (sb.Length == 0) return false;
        char last = sb[sb.Length - 1];
        return last == '-' || last == '\u2010';
    }

    private static void ProcessResourceFile(string content, SourceProductionContext context)
    {
        var xml = new XmlDocument();
        try
        {
            xml.LoadXml(content);
        }
        catch (Exception)
        {
            var desc = new DiagnosticDescriptor(
                        "RESW0002",
                        "Failed to load .resw file",
                        "An error was encountered while trying to parse the resw file, please check the resw document structure.",
                        "Problem",
                        DiagnosticSeverity.Error,
                        true);

            context.ReportDiagnostic(Diagnostic.Create(desc, Location.None));
            return;
        }

        var sb = new StringBuilder();
        var dataNodes = xml.SelectNodes("//data");

        _ = sb.AppendLine("// <auto-generated />");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace BiliCopilot.UI.Models.Constants;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("public enum StringNames");
        _ = sb.AppendLine("{");

        foreach (XmlNode dataNode in dataNodes)
        {
            var name = dataNode.Attributes["name"].Value;
            var valueNode = dataNode.SelectSingleNode("value");
            if (valueNode == null) continue;
            var value = valueNode.InnerText;

            _ = sb.AppendLine("    /// <summary>");
            if (value.Contains('\n'))
            {
                var lines = value.Split('\n');
                foreach (var line in lines)
                {
                    if (string.IsNullOrWhiteSpace(line))
                    {
                        continue;
                    }

                    var escapedLine = EscapeForXmlComment(line);
                    _ = sb.AppendLine($"    /// {escapedLine}");
                }
            }
            else
            {
                var escapedValue = EscapeForXmlComment(value);
                _ = sb.AppendLine($"    /// {escapedValue}");
            }

            _ = sb.AppendLine("    /// </summary>");
            _ = sb.AppendLine($"    {name},");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("}");
        context.AddSource("StringNames.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
